### ISSUE TITLE
Clean up maven dependencies

### ISSUE THREAD

**Issue by troggy** [37coins/longan-resource-bundle-client#1]
RestNucleousBoilerplate is overkill here.
It could be replaced with more fine grained deps:
- jackson-databind
- google-guava instead of the whole jax-rs just to use MultivalueMap
- DigestFilter.collectLeaves should be moved to the common library (as it is a very generic code)

**Comment by Gateway85** [comment]
replaced by: https://github.com/37coins/technicalDebt/issues/2
